config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/:id/edit' => 'users#edit'
  patch '/users/:id' => 'users#update' 
  resources :users
  
  get '/cars/new' => 'cars#new'
  resources :cars
  
  
  resources :reservations do
    member do
      put 'pickup'
      put 'returncar'
      put 'cancel'
    end
  end
  patch 'reservations/:id/cancel' => 'reservations#cancel'
  post 'reservations/:id/cancel' => 'reservations#cancel'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/reservation.rb
class Reservation < ApplicationRecord
    
  require 'date'
  enum reservationStatuses: [:Awaiting, :Active, :Complete, :Cancel]

  validates :reservationStatus, inclusion: {in: reservationStatuses}
  validates :checkOutTime, presence: true
  validates :expectedReturnTime, presence: true
  
  validate :orderTimeValidation
  
  def orderTimeValidation 
    if checkOutTime < Time.now || checkOutTime > Time.now + 7.days
      errors.add(:checkOutTime, "should within 7 days from now!")
    elsif expectedReturnTime < Time.now || expectedReturnTime > Time.now + 7.days
      errors.add(:expectedReturnTime, "should within 7 days from now!")
    elsif checkOutTime >= expectedReturnTime
      errors.add(:expectedReturnTime, "should be in the future of checkout time!")
    end 
  end
    
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  require 'date'
  Time.zone = 'Eastern Time (US & Canada)'
  
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :edit, :index, :new, :create, :pickup, :returncar, :cancel, :destroy]
  before_action :logged_in_as_admin, only: [:destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    if isAdmin? || isSuperAdmin?
      @reservations = Reservation.all
    else
      @reservations = Reservation.where(:user_id => session[:user_id]) || [] # return current user record or empty
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    # param1 = params[:param1]
    @reservation = Reservation.new
    # @reservation.update_attribute(:car_id, param1)
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    car_id = reservation_params[:car_id]
    user_id = reservation_params[:user_id]
    if user_id==""
      flash[:danger] = "You should select a user."
      redirect_to new_reservation_path(:param1 => car_id)
      return
    end
    unless Car.find(car_id).status == "Available"
      flash[:danger] = "This car is not available."
      redirect_to cars_path
      return
    end
    user = User.find(user_id)
    if user.available
      @reservation = Reservation.new(reservation_params)
      if @reservation.save
        flash[:success] = 'Reservation was successfully created.'
        PickupCheckJob.set(wait_until: @reservation.checkOutTime + 30.minutes).perform_later(@reservation.id)
        redirect_to @reservation
        car = Car.find(@reservation.car_id)
        car.update_attribute(:status, "Reserved")
        user.update_attribute(:available, false)
      else
        if @reservation.errors.any?
          @reservation.errors.full_messages.each do |message|
            flash[:errors] = message
          end
        end
        redirect_to new_reservation_path(:param1 => car_id)
      end
    else
      flash[:danger] = "You have a car in hold, and cannot reserve another car until you return it."
      redirect_to user
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    if @reservation.update(reservation_params)
      flash[:success] = 'Reservation was successfully updated.'
      redirect_to @reservation
    else
      render :edit
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    User.find(@reservation.user_id).update_attribute(:available, true)
    Car.find(@reservation.car_id).update_attribute(:status, "Available")
    @reservation.destroy
    flash[:success] = 'Reservation deleted!'
    redirect_to reservations_url
  end

  def pickup
    @reservation = Reservation.find(params[:id])
    if @reservation.checkOutTime > Time.now
      flash[:error] = 'You need to wait to pick up the car!'
      redirect_to @reservation
    elsif @reservation.update_attribute(:pickUpTime, Time.now)
      flash[:success] = 'Car was successfully picked up. Have a good time!'
      @reservation.update_attribute(:reservationStatus, "Active")
      car = Car.find(@reservation.car_id)
      car.update_attribute(:status, "CheckedOut")
      ReturnCheckJob.set(wait_until: @reservation.expectedReturnTime + 60).perform_later(@reservation.id)
      redirect_to @reservation
    end
  end

  def returncar
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attribute(:returnTime, Time.now)
      flash[:success] = 'Car was successfully returned. Thank you!'
      @reservation.update_attribute(:reservationStatus, "Complete")
      user = User.find(@reservation.user_id)
      car = Car.find(@reservation.car_id)
      car.update_attribute(:status, "Available")
      price = car.hourlyRentalRate
      hold_time = (@reservation.returnTime - @reservation.pickUpTime)/3600.0 # convert to hours
      charge = user.rentalCharge + price*hold_time
      user.update_attribute(:rentalCharge, charge) 
      # user.update_attribute(:notification, "You have pending charge!")
      user.update_attribute(:available, true)
      redirect_to @reservation
    end
  end

  # PATCH/PUT /reservations/1
  def cancel
    @reservation = Reservation.find(params[:id])
    if ["Active", "Complete", "Cancel"].include? @reservation.reservationStatus
      flash[:danger] = "Reservation cannot be canceled!"
      redirect_to reservations_url
      return
    end
    if @reservation.update_attribute(:reservationStatus, "Cancel")
      User.find(@reservation.user_id).update_attribute(:available, true)
      Car.find(@reservation.car_id).update_attribute(:status, "Available")
      flash[:success] = "Reservation successfully canceled!"
      redirect_to @reservation
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:registrationNumber, :checkOutTime, :pickUpTime, :expectedReturnTime, :returnTime, :reservationStatus, :user_id, :car_id)
    end
  
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_cancel.html.erb
<%= form_for @reservation, url: {action: "cancel"}, method: :post do |form| %>
  <% if @reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

        <ul>
          <% @reservation.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  
  <%= form.label "Car plate number: " %>
  <%= Car.find(@reservation.car_id).licensePlateNumber %><br>
  
  <%= form.label "User id and name: " %>
  <% user = User.find(@reservation.user_id) %>
  <%= "#{user.id} - #{user.name}" %><br>
  
  <%= form.label "Check out time:" %><br>
  <%= @reservation.checkOutTime %><br>

  <%= form.label "Expected return time:" %> <br>
  <%= @reservation.expectedReturnTime %><br>

  <%= form.submit "Cancel this reservation", class: "btn btn-primary", data: { confirm: 'Cancel this reservation?' }%><br>
    
<% end %>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

        <ul>
          <% reservation.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <% param1 = params[:param1] %>
  
  <%= form.label "Car plate number: " %>
  <%= Car.find(param1).licensePlateNumber %><br>
  
  <%= form.hidden_field :car_id, value: param1 %>
  <% if isAdmin? || isSuperAdmin? %>
    <%= form.label "User id and name: " %>
    <%= form.collection_select :user_id, User.all, :id, lambda {|u| "#{u.id}- #{u.name}"}, {:prompt => "Please select user id"} %><br>
  <% else %>
    <%= form.hidden_field :user_id, value: session[:user_id] %><br>
  <% end %>
  
  <%= form.label "Check out time:" %><br>
  <%= form.datetime_select :checkOutTime, id: :reservation_checkOutTime %><br>



  <%= form.label "Expected return time:" %> <br>
  <%= form.datetime_select :expectedReturnTime, id: :reservation_expectedReturnTime %><br>

  <%= form.submit "Make a reservation", class: "btn btn-primary" %><br>
    
<% end %>

app/views/reservations/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Editing Reservation</h1>

<% if isAdmin? || isSuperAdmin? %>
  <%= render 'form', reservation: @reservation %>
<% elsif isCustomer? %>
  <%= render 'cancel', reservation: @reservation %>
<% end %>

<%= link_to 'Show', @reservation %> |
<% if isAdmin? || isSuperAdmin? %>
  <%= link_to 'List', reservations_path %> |
<% end %>
<%= link_to "Back", :back %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>Checkouttime</th>
      <th>Pickuptime</th>
      <th>Expectedreturntime</th>
      <th>Returntime</th>
      <th>User name</th>
      <th>Car licensePlateNumber</th>
      <th>Reservationstatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        
        <td><%= reservation.checkOutTime %></td>
        <td><%= reservation.pickUpTime %></td>
        <td><%= reservation.expectedReturnTime %></td>
        <td><%= reservation.returnTime %></td>
        <td>
          <% user=User.find_by_id(reservation.user_id) %>
          <%= link_to user.name, user %>
        </td>
        <td>
          <% car=Car.find_by_id(reservation.car_id) %>
          <%= link_to car.licensePlateNumber, car %>
        </td>
        <td><%= reservation.reservationStatus %></td>
        <td><%= link_to 'Show', reservation %></td>
        <% if isAdmin? || isSuperAdmin? %>
          <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
          <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif isCustomer? && !["Complete","Cancel"].include?(reservation.reservationStatus) %>
          <td><%= link_to 'Cancel', edit_reservation_path(reservation) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', cars_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'List', reservations_path %> |
<%= link_to 'Back', :back %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car Plate Number:</strong>
  <%=  Car.find(@reservation.car_id).licensePlateNumber %>
</p>

<p>
  <strong>Checkouttime:</strong>
  <%= @reservation.checkOutTime %>
</p>

<% if @reservation.reservationStatus == "Awaiting" %>
    <p>
      <strong>Expectedreturntime:</strong>
      <%= @reservation.expectedReturnTime %>
    </p>
<% end %>

<% if @reservation.reservationStatus != "Awaiting" %>

    <% if @reservation.reservationStatus != "Cancel" %>
        <p>
          <strong>Pickuptime:</strong>
          <%= @reservation.pickUpTime %>
        </p>
    <% end %>

    <% if @reservation.reservationStatus == "Complete" %>
        <p>
          <strong>Returntime:</strong>
          <%= @reservation.returnTime %>
        </p>
    <% end %>

    <% if @reservation.reservationStatus == "Active" %>
        <p>
          <strong>Expectedreturntime:</strong>
          <%= @reservation.expectedReturnTime %>
        </p>
    <% end %>

<% end %>

<p>
  <strong>Reservationstatus:</strong>
  <%= @reservation.reservationStatus %>
</p>


<% # buttons that display on customer view %>
<% if @reservation.reservationStatus == "Awaiting" %>
    <%= button_to "pickup", pickup_reservation_path(@reservation), :method => :put %>
<% end %>

<% if @reservation.reservationStatus == "Active" %>
    <%= button_to "return", returncar_reservation_path(@reservation), :method => :put %>
<% end %>

<%if isAdmin? || isSuperAdmin? %>
  <%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<% end %>
<%= link_to 'Back', reservations_path %>