config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/:id/edit' => 'users#edit'
  patch '/users/:id' => 'users#update' 
  resources :users
  
  get '/cars/new' => 'cars#new'
  resources :cars
  
  
  resources :reservations do
    member do
      put 'pickup'
      put 'returncar'
      put 'cancel'
    end
  end
  patch 'reservations/:id/cancel' => 'reservations#cancel'
  post 'reservations/:id/cancel' => 'reservations#cancel'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/car.rb
class Car < ApplicationRecord
    
  enum styles: [:Coupe, :Sedan, :SUV]
  enum statuses: [:CheckedOut, :Available, :Reserved]

  validates :licensePlateNumber, presence: true, uniqueness: {case_sensitive: false}, length: {is: 7}
  validates :manufacturer, presence: true
  validates :model, presence: true
  validates :hourlyRentalRate, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :style, presence: true, inclusion: {in: styles}
  validates :location, presence: true
  validates :status, presence: true, inclusion: {in: statuses}
  
  def isAvailable?
    status == "Available"
  end
  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include CarsHelper
  before_action :logged_in_user, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :logged_in_as_admin, only: [:new, :destroy, :edit, :update]
  
  # GET /cars
  # GET /cars.json
  def index
    @q_cars = Car.ransack(params[:q])
    @cars = @q_cars.result().paginate(page: params[:page])
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
<<<<<<< HEAD
    @car = Car.find(params[:model])
=======
    @car = Car.find(params[:id])
>>>>>>> 7aeb37be93b12094686fdafe4bcbee0d54f2379b
  end

  # GET /cars/new
  # this should redirect to create html
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
<<<<<<< HEAD
    @car = Car.find(params[:licensePlateNumber])
    @car.status = params[:status]
=======
    @car = Car.find(params[:id])
>>>>>>> 7aeb37be93b12094686fdafe4bcbee0d54f2379b
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:success] = "New car added!"
      redirect_to @car
    else
      render :new
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    @car = Car.find(params[:id])
    if @car.update_attributes(car_params)
      flash[:sucess] = "Car info updated."
      redirect_to @car
    else
      render :edit
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id]).destroy
    flash[:success] = 'Car deleted.'
    redirect_to cars_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_car
    #   @car = car.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:licensePlateNumber, :manufacturer, :model, :hourlyRentalRate, :style, :location, :status)  
    end
    
end

app/helpers/cars_helper.rb
module CarsHelper
  
  def car_fields 
    # fields to be displayed on front-end view
    [:licensePlateNumber, :manufacturer, :status] 
  end
    
  def action 
    action_name == 'advanced_search' ? :post : :get 
  end
  
  def display_car_sorted_column_headers(search) 
    car_fields.each_with_object('') do |field, string| 
      string << content_tag(:th, sort_link(search, field, {}, method: action)) 
    end 
  end
  
  def display_car_search_results(objects) 
    objects.each_with_object('') do |object, string| 
      string << content_tag(:tr, display_car_search_results_row(object)) 
    end 
  end
  
  def display_car_search_results_row(object)
    fieldCount = 0
    car_fields.each_with_object('') do |field, string|
      if fieldCount == 0
        string << content_tag(:td, link_to(object.send(field), '/cars/' + object.id.to_s))
      else
        string << content_tag(:td, object.send(field))
      end
      
      fieldCount += 1
      
    end
    .html_safe
  end
  
end

app/views/cars/_form.html.erb
    <%= form_for(@car) do |f| %>
      <% if @car.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@car.errors.count, "error") %>.
          </div>
          <ul>
          <% @car.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <%= f.label :licensePlateNumber %>
      <%= f.text_field :licensePlateNumber %>
      <br>
      <%= f.label :manufacturer %>
      <%= f.text_field :manufacturer %>
      <br>
      <%= f.label :model %>
      <%= f.text_field :model %>
      <br>
      <%= f.label :hourlyRentalRate %>
      <%= f.text_field :hourlyRentalRate %>
      <br>
      <%= f.label :style %>
      <%= f.collection_select :style, Car.styles, :first, :first, {:prompt => "Please select car status"} %>
      <br>
      <%= f.label :location %>
      <%= f.text_field :location %>
      <br>
      <%= f.label :status %>
      <%= f.collection_select :status, Car.statuses, :first, :first, {:prompt => "Please select car status"} %> 
      <br>
      <%= f.submit "Submit car info", class: "btn btn-primary" %>
    <% end %>
    

app/views/cars/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Edit car info</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<% provide(:title, 'All cars') %>
<h1>View and Search cars</h1>

<%= search_form_for @q_cars do |f| %>
  <%= f.label :location %>
  <%= f.search_field :location_cont %><br>
  <%= f.label :manufacturer %>
  <%= f.collection_select :manufacturer_cont, Car.select("distinct manufacturer"), :manufacturer, :manufacturer, {:include_blank => "Please select car manufacturer"} %><br>
  <%= f.label :model %>
  <%= f.collection_select :model_cont, Car.select("distinct model"), :model, :model, {:include_blank => "Please select car model"} %><br>
  <%= f.label :style %>
  <%= f.collection_select :style_cont, Car.select("distinct style"), :style, :style, {:include_blank => "Please select car style"} %><br>
  <%= f.label :status %>
  <%= f.collection_select :status_cont, Car.select("distinct status"), :status, :status, {:include_blank => "Please select car status"} %><br>
  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>

<%= will_paginate %>
<%= content_tag :table, class: 'table' do %>
  <%= content_tag :thead, display_car_sorted_column_headers(@q_cars), nil, false %>
  <%= content_tag :tbody, display_car_search_results(@cars), nil, false %>
<% end %>
<%= will_paginate %>

app/views/cars/new.html.erb
<% provide(:title, "Add new car") %>
<h1>Add new car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<% provide(:title, @car.manufacturer+' - '+@car.model) %>

<h1>
  <%= @car.manufacturer %>
</h1>
<div class="row">
  <aside class="col-md-4">
    <section class="car_info">
      
        <%= label_tag "Model" %> :
        <%= @car.model %><br>
        <%= label_tag "License #" %> :
        <%= @car.licensePlateNumber %><br>
        <%= label_tag "Hourly Rent Rate" %> :
        <%= '$%.2f per hour' % @car.hourlyRentalRate %><br>
        <%= label_tag "Car Style" %> :
        <%= @car.style %><br>
        <%= label_tag "Location" %> :
        <%= @car.location %><br>
        <%= label_tag "Status" %> :
        <%= @car.status %><br>
      
    </section>
  </aside>
</div>


<% if @car.isAvailable? %>
  <%= link_to 'Reserve', new_reservation_path(:param1 => @car.id) %> |
<% end %>
<% if isAdmin? || isSuperAdmin? %>
  <%= link_to 'Edit', edit_car_path(@car) %> |
  <%= link_to "Delete", @car, method: :delete, data: { confirm: "Delete this car?" } %> |
<% end %>
<%= link_to 'List', cars_path %> |
<%= link_to 'Back', :back %>