config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/:id/edit' => 'users#edit'
  patch '/users/:id' => 'users#update' 
  resources :users
  
  get '/cars/new' => 'cars#new'
  resources :cars
  
  
  resources :reservations do
    member do
      put 'pickup'
      put 'returncar'
      put 'cancel'
    end
  end
  patch 'reservations/:id/cancel' => 'reservations#cancel'
  post 'reservations/:id/cancel' => 'reservations#cancel'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "Car Rental App", user_path(current_user), id: :logo %>
    <% else %>
      <%= link_to "Car Rental App", root_path, id: :logo %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Cars <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Search & view cars", cars_path %></li>
              <% if isAdmin? || isSuperAdmin? %>
                <li><%= link_to "Add new car", new_car_path %></li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Reservations <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Search & view reservations", reservations_path %></li>
                <% if isAdmin? || isSuperAdmin? %>
                  <li><%= link_to "Add new reservation", cars_path %></li>
                <% end %>
              </ul>
            </li>
          <% if isAdmin? || isSuperAdmin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Users <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Search & view users", users_path %></li>
                <li><%= link_to "Add new user", new_user_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= display_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>" role="alert"><%= message %></div>
      <% end %>
      
      <%= yield %>
      
    </div>
    
  </body>
</html>